[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/', '@openzeppelin/=lib/openzeppelin-contracts/', 'erc721a=lib/ERC721A']

# See more config options https://github.com/gakonst/foundry/tree/master/config